In [2]:
import torch
import numpy as np

### Basic tensor concepts

In [115]:
#1-d tensor
torch.zeros(4)

tensor([0., 0., 0., 0.])

In [113]:
#2-d tensor
torch.rand(1, 4)

tensor([[0.9762, 0.6915, 0.8543, 0.9701]])

In [114]:
#2-d tensor
torch.rand(2, 4)

tensor([[0.0233, 0.6764, 0.0156, 0.2080],
        [0.9866, 0.0606, 0.2551, 0.0233]])

In [116]:
#3-d tensor
torch.rand(1, 1, 4)

tensor([[[0.6308, 0.6515, 0.7228, 0.4125]]])

In [118]:
#3-d tensor
torch.rand(2, 3, 4)

tensor([[[0.9901, 0.4289, 0.2375, 0.3448],
         [0.8833, 0.0459, 0.6079, 0.4037],
         [0.6414, 0.4347, 0.1760, 0.0192]],

        [[0.5089, 0.0767, 0.6033, 0.0223],
         [0.8928, 0.7115, 0.2929, 0.8741],
         [0.8262, 0.4738, 0.5560, 0.7393]]])

In [121]:
#4-d tensor
torch.rand(1, 1, 1, 4)

tensor([[[[0.1224, 0.3894, 0.1016, 0.4055]]]])

In [125]:
#4-d tensor
torch.zeros(5,3,2,4)

tensor([[[[0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.]]],


        [[[0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.]]],


        [[[0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.]]],


        [[[0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.]]],


        [[[0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.]]]])

### Indexing tensors

In [142]:
tensor = torch.rand(5, 4)*10 #multiplying with 10 because it is easy to visualize
tensor

tensor([[8.4411, 3.1186, 9.3986, 1.5405],
        [9.8858, 7.9934, 4.5518, 5.2520],
        [3.9284, 5.1998, 3.9715, 7.3187],
        [9.0004, 2.9226, 8.3042, 1.3898],
        [1.8537, 1.2443, 0.5550, 3.2094]])

In [143]:
tensor[:, 2]#2nd indexed column

tensor([9.3986, 4.5518, 3.9715, 8.3042, 0.5550])

In [138]:
tensor[1, 2]

tensor(3.5128)

In [139]:
tensor1 = torch.rand(3, 2, 4)*10
tensor1

tensor([[[2.1061, 3.0881, 8.7027, 2.9360],
         [2.0008, 1.4596, 2.8642, 2.1212]],

        [[3.7865, 2.9654, 8.8403, 8.9732],
         [8.0782, 6.2419, 2.8244, 4.2657]],

        [[3.5661, 1.1549, 5.1745, 7.7361],
         [8.2555, 7.6453, 5.2620, 4.2200]]])

In [144]:
tensor1[:, 1, 3]# 3rd indexed column and first index of each row

tensor([2.1212, 4.2657, 4.2200])

In [146]:
torch.cat([tensor,tensor], dim=1)

tensor([[8.4411, 3.1186, 9.3986, 1.5405, 8.4411, 3.1186, 9.3986, 1.5405],
        [9.8858, 7.9934, 4.5518, 5.2520, 9.8858, 7.9934, 4.5518, 5.2520],
        [3.9284, 5.1998, 3.9715, 7.3187, 3.9284, 5.1998, 3.9715, 7.3187],
        [9.0004, 2.9226, 8.3042, 1.3898, 9.0004, 2.9226, 8.3042, 1.3898],
        [1.8537, 1.2443, 0.5550, 3.2094, 1.8537, 1.2443, 0.5550, 3.2094]])

In [40]:
tensor1

tensor([[[0.8677, 0.8819, 0.4480, 0.9139],
         [0.6970, 0.0644, 0.5178, 0.1507],
         [0.6624, 0.0799, 0.1040, 0.3082],
         [0.9845, 0.3536, 0.0063, 0.5502],
         [0.0522, 0.7002, 0.8409, 0.7145]],

        [[0.6454, 0.3798, 0.1844, 0.6193],
         [0.3253, 0.1867, 0.4642, 0.8126],
         [0.7502, 0.8258, 0.1274, 0.8813],
         [0.6805, 0.1756, 0.4904, 0.3681],
         [0.8669, 0.5823, 0.8548, 0.4905]],

        [[0.6189, 0.7849, 0.4686, 0.4055],
         [0.1762, 0.8459, 0.4673, 0.1757],
         [0.5000, 0.5959, 0.4824, 0.6886],
         [0.2114, 0.3571, 0.3556, 0.9552],
         [0.3899, 0.7633, 0.2842, 0.3313]]])

### Now the "difficult" concept - matrix multiplication

In [152]:
a = [[1,2],[5,6]]

In [153]:
b = [9, 0]

In [154]:
tensor_a = torch.tensor(a)
tensor_b = torch.tensor(b)

In [155]:
tensor_a.matmul(tensor_b)

tensor([ 9, 45])

#### Multi dimensional matrix multiplication

In [156]:
m = [[1, 1], [1, 1]]

In [157]:
c = [[ m,m,m ]]

In [158]:
d = [[ m, m, m],
     [ m, m, m],
    [m, m, m]]

In [159]:
tensor_c = torch.tensor(c)
tensor_d = torch.tensor(d)

In [160]:
tensor_c.shape, tensor_d.shape

(torch.Size([1, 3, 2, 2]), torch.Size([3, 3, 2, 2]))

In [161]:
tensor_c.matmul(tensor_d).shape

torch.Size([3, 3, 2, 2])

In [162]:
tensor_d.matmul(tensor_c)

tensor([[[[2, 2],
          [2, 2]],

         [[2, 2],
          [2, 2]],

         [[2, 2],
          [2, 2]]],


        [[[2, 2],
          [2, 2]],

         [[2, 2],
          [2, 2]],

         [[2, 2],
          [2, 2]]],


        [[[2, 2],
          [2, 2]],

         [[2, 2],
          [2, 2]],

         [[2, 2],
          [2, 2]]]])